---
name: Tanya
surname: Strydom
profilepic: "profile.png"
#position: "Professor"
#address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +46 76 567 8299
www: "tanyadoesscience.com"
email: "tanya.strydom@icloud.com"
twitter: TanyaS_08
github: TanyaS08
#orcid: 0000-0001-6067-1349
#google scholar: AkDd5u8AAAAJ
headcolor: 414141 # use black color
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
csl: ecology.csl # change this if you want to use other citation styles
nocite: '*@' # don't change this if you want to print out all the refs
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae);library(tibble);library(rorcid)
```

# Research Interests

microclimates; species interactions; functional traits; ecoinformatics

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~Advisor, ~ Year, ~ Institution, ~ Where,
  "Master of Science: Ecology and Biodiversity","Advisor: K. Hylander, PhD", "2018-20", "Stockholm University", "Stockholm, Sweden",
  "Master of Science: Ecology and Biodiversity","Thesis: Thesis: Declines and increases in northern and southern plant populations after changes in the microclimate", "2018-20", "Stockholm University", "Stockholm, Sweden",
  "Bachelor of Science (Honours): Plant Sciences","Advisor: P.C. le Roux, PhD", "2017", "University of Pretoria", "Pretoria, South Africa",
  "Bachelor of Science (Honours): Plant Sciences","Thesis: Thesis: Bush encroachment in South Africa’s montane grasslands: the impact of Leucosidea sericea on microclimate and vegetation", "2017", "University of Pretoria", "Pretoria, South Africa",
  "Bachelor of Science: Ecology", NA, "2014-16", "University of Pretoria", "Pretoria, South Africa"
) %>% 
  detailed_entries(with=Degree, when=Year, what=Institution, where=Where, why=Advisor)
```

# Research Experience

```{r}
tribble(
  ~ Project, ~Supervisor, ~Description, ~ Year,
  #For PFTC
  "Plant functional trait responses to elevation and fire","V. Vandvik, PhD and B.J. Enquist, PhD", "Attended the 5th Plants Functional Traits Course in Peru co-hosted by the Univesity of Bergen and Arizona University.", "2020",
  "Plant functional trait responses to elevation and fire","V. Vandvik, PhD and B.J. Enquist, PhD", "Theory on plant functional traits and their relationships with broader ecological processes.", "2020",
  "Plant functional trait responses to elevation and fire","V. Vandvik, PhD and B.J. Enquist, PhD", "Practical elements include: experimental design, data collection and curation, and report writing.", "2020",
  #For MSc
  "Plant vital rates along microclimate gradients.", "K. Hylander, PhD","Masters degree research project.", "2019-20",
  "Plant vital rates along microclimate gradients.", "K. Hylander, PhD","Focused on the variation of plant population vital rates along microclimate gradients and the role of historic climatic conditions.", "2019-20",
  #For interactions
  "Plant-pollinator interactions in different microsites", "J. Ehrlén, PhD and A. Tack, PhD", "A Masters level course research project.", "2019",
  "Plant-pollinator interactions in different microsites", "J. Ehrlén, PhD and A.Tack, PhD", "Independently worked on hypothesis formulation and experimental design.", "2019",
    #For marion
    "Changes in plant functional traits at fine-scales", "P.C. le Roux, PhD", "Collecting and processing plant functional traits on sub-Antarctic Marion Island.", "2018",
  "Changes in plant functional traits at fine-scales", "P.C. le Roux, PhD", "Research focused on looking at changes in plant functional traits along microclimate gradients.", "2018",
  #Honours
  "The impact of an encroaching species on vegetation and microclimate", "P.C. le Roux, PhD","Honours degree research project.", "2017",
  "The impact of an encroaching species on vegetation and microclimate", "P.C. le Roux, PhD","Research focused on the concepts of biotic interactions, ecosystem engineering and habitat modification.", "2017") %>% 
  detailed_entries(with=Project, when=Year, why=Description, what = Supervisor)


```

# Other Skills

```{r}
tribble(
  ~ Project, ~Supervisor,
  "Statistical Analysis","generalized mixed-effect modelling; mulitvariate analysis; Bayesian analysis" ,
  "Academic Writing", "assessed at various levels; literature reviews; research proposals; research reports; popular articles",
  "Oral Communication", "masters level course; presented various settings",
  "Peer Review", "assisted (PLoS ONE, 2018); second-round reviewer (Plant Ecology, 2019)",
  "Image Analysis", "ImageJ; Adobe Photoshop",
  "Spatial Analysis", "honours level course focused on spatial analysis in ecology; ArcGIS; Maxent",
  "Language Skills", "English and Afrikaans as a native speaker; conversational in German") %>% 
  detailed_entries(with=Project, what = Supervisor)


```

# Written Works

## PUBLICATIONS
```{r}

library(dplyr)

scholar::get_publications("AkDd5u8AAAAJ", flush = TRUE) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  mutate(doi = "10.1111/gcb.14904") %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("Published.bib")

bibliography_entries("Published.bib")

```

## MANUSCRIPTS UNDER REVIEW

```{r}

RefManageR::BibEntry(bibtype="Misc", key = "EvoEcol2020", date = "", title = "International scientists need better support during global emergencies", author = "Sonya Geange and Jonathan von Oppen and Sara Middleton and Tasha-Leigh Gauthier and Tanya Strydom and Ragnhild Gya and...", journal = "Ecology and Evolution", pubstate = "submitted") %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib("Under_Review.bib")

bibliography_entries("Under_Review.bib")

```

## POPULAR ARTICLES

```{r}

RefManageR::BibEntry(bibtype="Misc", key = "peru2020", date = "2020", title = "International scientists need better support during global emergencies", author = "Sehoya Cotner and Brian J. Enquist and Julia Chacon and Brian Maitner and William Farfan-Rios and Sean Michaletz and...", url = "https://www.timeshighereducation.com/blog/international-scientists-need-better-support-during-global-emergencies", journaltitle = "Times Higher Education") %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib("Popular_Articles.bib")

bibliography_entries("Popular_Articles.bib")

```

# Funding and Awards

```{r}

tribble(
  ~Institution, ~Award, ~Year,
  'Awarded by: University of Pretoria',  "Qualified for the UP Postgraduate Masters Research Bursary.", "2018",
  'Awarded by: University of Pretoria',  "Awarded the 3rd year Undergraduate Mentorship Bursary.", "2016"
) %>% 
  detailed_entries(
    what = Institution,
    with = Award, 
    when = Year
  )

```

# References

```{r}
tribble(
  ~Name, ~Title, ~Contact, ~Number,
  'Peter C. le Roux, Ph.D.',  "Assistant professor of Ecology and Biodiversity, University of Pretoria", "peter.leroux@up.ac.za", "+27 (0)12 420 6761",
  'Kristoffer Hylander, Ph.D.',  "Professor of Ecolgy,  Department of Ecology, Environment and Plant Sciences, Stockholm University", "kristoffer.hylander@su.se", NA,
  'Sehoya Cotner, Ph.D.',  "Professor of Biology Teaching and Learning, University of Minnesota", "sehoya@umn.edu", "+1 (612) 626 2385"
) %>% 
  detailed_entries(
    where = Contact,
    with = Name, 
    what = Title,
    when = Number
  )
```